Add ability to release with outdated deps to release script

diff --git a/scripts/prerelease b/scripts/prerelease
--- a/scripts/prerelease
+++ b/scripts/prerelease
@@ -1,7 +1,16 @@
 #!/usr/bin/env bash
 set -eufo pipefail
-npm out --long
-npm whoami
+
+echo "Publishing as $(npm whoami)."
+
+if ! npm outdated --long; then
+  read -rp "Continue? [y/N] " choice
+  if [[ "${choice-n}" != 'y' ]]; then
+    echo 'Package distribution aborted.'
+    exit 2
+  fi
+fi
+
 npm run build
 transcribe --url 'https://github.com/fluture-js/fluture-hooks/blob/master/{filename}#L{line}' index.mjs > README.md
 git add README.md
